### Respuestas al examen de laboratorio. Curso 2022-23
### Nombre del alumno: 
### Grupo al que pertenece:

### A continuación debe escribir las peticiones HTTP que dan
### solución a las cuestiones planteadas puede añadir todos 
### los comentarios que estime oportuno

@BASE = http://127.0.0.1:8081/api/v1
